### ISSUE TITLE
Add assert_block

### ISSUE THREAD

**Issue by cdemyanovich** [seattlerb/minitest_tu_shim#1]
In attempting to use minitest via minitest-rails and minitest_tu_shim on a Rails 3.2.14 app running on Ruby 1.8.7, I encountered many errors like

```
"NoMethodError: undefined method `assert_block'..."
```

`assert_block` was being called from `assert_response`, `assert_template`, or `assert_redirected_to` in controller tests.

While `assert_block` [exists](http://ruby-doc.org/stdlib-1.8.7/libdoc/test/unit/rdoc/Test/Unit/Assertions.html#method-i-assert_block) in the standard library for Ruby 1.8.7, it was removed from minitest 4.6 and later. Adding `assert_block` to minitest_tu_shim would allow use of minitest with Rails 3 apps on Ruby 1.8.7

Here are the gem versions I'm using.

```
$ gem list minitest

*** LOCAL GEMS ***

minitest (4.7.5)
minitest-rails (0.9.2)
minitest_tu_shim (1.3.2)
```

```
$ ruby -v
ruby 1.8.7 (2011-02-18 patchlevel 334) [i686-darwin12.0.0]
```

Rails 3.2.14

**Comment by zenspider** [comment]
Ugh. `assert_block` is soooo lame.

**Comment by zenspider** [comment]
OK. This is released.

**Comment by cdemyanovich** [comment]
Works well. Thanks!
